/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    // Pokemon type FROM gradient classes
    "from-pokemon-normal",
    "from-pokemon-fire",
    "from-pokemon-water",
    "from-pokemon-electric",
    "from-pokemon-grass",
    "from-pokemon-ice",
    "from-pokemon-fighting",
    "from-pokemon-poison",
    "from-pokemon-ground",
    "from-pokemon-flying",
    "from-pokemon-psychic",
    "from-pokemon-bug",
    "from-pokemon-rock",
    "from-pokemon-ghost",
    "from-pokemon-dragon",
    "from-pokemon-dark",
    "from-pokemon-steel",
    "from-pokemon-fairy",

    "from-pokemon-normal/50",
    "from-pokemon-fire/50",
    "from-pokemon-water/50",
    "from-pokemon-electric/50",
    "from-pokemon-grass/50",
    "from-pokemon-ice/50",
    "from-pokemon-fighting/50",
    "from-pokemon-poison/50",
    "from-pokemon-ground/50",
    "from-pokemon-flying/50",
    "from-pokemon-psychic/50",
    "from-pokemon-bug/50",
    "from-pokemon-rock/50",
    "from-pokemon-ghost/50",
    "from-pokemon-dragon/50",
    "from-pokemon-dark/50",
    "from-pokemon-steel/50",
    "from-pokemon-fairy/50",

    // Pokemon type TO gradient classes
    "to-pokemon-normal",
    "to-pokemon-fire",
    "to-pokemon-water",
    "to-pokemon-electric",
    "to-pokemon-grass",
    "to-pokemon-ice",
    "to-pokemon-fighting",
    "to-pokemon-poison",
    "to-pokemon-ground",
    "to-pokemon-flying",
    "to-pokemon-psychic",
    "to-pokemon-bug",
    "to-pokemon-rock",
    "to-pokemon-ghost",
    "to-pokemon-dragon",
    "to-pokemon-dark",
    "to-pokemon-steel",
    "to-pokemon-fairy",

    "to-pokemon-normal/50",
    "to-pokemon-fire/50",
    "to-pokemon-water/50",
    "to-pokemon-electric/50",
    "to-pokemon-grass/50",
    "to-pokemon-ice/50",
    "to-pokemon-fighting/50",
    "to-pokemon-poison/50",
    "to-pokemon-ground/50",
    "to-pokemon-flying/50",
    "to-pokemon-psychic/50",
    "to-pokemon-bug/50",
    "to-pokemon-rock/50",
    "to-pokemon-ghost/50",
    "to-pokemon-dragon/50",
    "to-pokemon-dark/50",
    "to-pokemon-steel/50",
    "to-pokemon-fairy/50",

    // Pokemon type BORDER classes
    "border-pokemon-normal",
    "border-pokemon-fire",
    "border-pokemon-water",
    "border-pokemon-electric",
    "border-pokemon-grass",
    "border-pokemon-ice",
    "border-pokemon-fighting",
    "border-pokemon-poison",
    "border-pokemon-ground",
    "border-pokemon-flying",
    "border-pokemon-psychic",
    "border-pokemon-bug",
    "border-pokemon-rock",
    "border-pokemon-ghost",
    "border-pokemon-dragon",
    "border-pokemon-dark",
    "border-pokemon-steel",
    "border-pokemon-fairy",

    // Pokemon type BACKGROUND classes
    "bg-pokemon-normal",
    "bg-pokemon-fire",
    "bg-pokemon-water",
    "bg-pokemon-electric",
    "bg-pokemon-grass",
    "bg-pokemon-ice",
    "bg-pokemon-fighting",
    "bg-pokemon-poison",
    "bg-pokemon-ground",
    "bg-pokemon-flying",
    "bg-pokemon-psychic",
    "bg-pokemon-bug",
    "bg-pokemon-rock",
    "bg-pokemon-ghost",
    "bg-pokemon-dragon",
    "bg-pokemon-dark",
    "bg-pokemon-steel",
    "bg-pokemon-fairy",

    // HOVER variants with opacity
    "hover:bg-pokemon-normal/60",
    "hover:bg-pokemon-fire/60",
    "hover:bg-pokemon-water/60",
    "hover:bg-pokemon-electric/60",
    "hover:bg-pokemon-grass/60",
    "hover:bg-pokemon-ice/60",
    "hover:bg-pokemon-fighting/60",
    "hover:bg-pokemon-poison/60",
    "hover:bg-pokemon-ground/60",
    "hover:bg-pokemon-flying/60",
    "hover:bg-pokemon-psychic/60",
    "hover:bg-pokemon-bug/60",
    "hover:bg-pokemon-rock/60",
    "hover:bg-pokemon-ghost/60",
    "hover:bg-pokemon-dragon/60",
    "hover:bg-pokemon-dark/60",
    "hover:bg-pokemon-steel/60",
    "hover:bg-pokemon-fairy/60",

    // Active variants with opacity
    "active:bg-pokemon-normal",
    "active:bg-pokemon-fire",
    "active:bg-pokemon-water",
    "active:bg-pokemon-electric",
    "active:bg-pokemon-grass",
    "active:bg-pokemon-ice",
    "active:bg-pokemon-fighting",
    "active:bg-pokemon-poison",
    "active:bg-pokemon-ground",
    "active:bg-pokemon-flying",
    "active:bg-pokemon-psychic",
    "active:bg-pokemon-bug",
    "active:bg-pokemon-rock",
    "active:bg-pokemon-ghost",
    "active:bg-pokemon-dragon",
    "active:bg-pokemon-dark",
    "active:bg-pokemon-steel",
    "active:bg-pokemon-fairy",

    // Light variants with opacity
    "from-pokemon-normal/10",
    "from-pokemon-fire/10",
    "from-pokemon-water/10",
    "from-pokemon-electric/10",
    "from-pokemon-grass/10",
    "from-pokemon-ice/10",
    "from-pokemon-fighting/10",
    "from-pokemon-poison/10",
    "from-pokemon-ground/10",
    "from-pokemon-flying/10",
    "from-pokemon-psychic/10",
    "from-pokemon-bug/10",
    "from-pokemon-rock/10",
    "from-pokemon-ghost/10",
    "from-pokemon-dragon/10",
    "from-pokemon-dark/10",
    "from-pokemon-steel/10",
    "from-pokemon-fairy/10",

    "border-pokemon-normal/20",
    "border-pokemon-fire/20",
    "border-pokemon-water/20",
    "border-pokemon-electric/20",
    "border-pokemon-grass/20",
    "border-pokemon-ice/20",
    "border-pokemon-fighting/20",
    "border-pokemon-poison/20",
    "border-pokemon-ground/20",
    "border-pokemon-flying/20",
    "border-pokemon-psychic/20",
    "border-pokemon-bug/20",
    "border-pokemon-rock/20",
    "border-pokemon-ghost/20",
    "border-pokemon-dragon/20",
    "border-pokemon-dark/20",
    "border-pokemon-steel/20",
    "border-pokemon-fairy/20",

    // Your custom background gradients
    "bg-linear-65",
    "bg-linear-90",
  ],
};
